branch: [ master, dev ]

pipeline:

  test:
    image: shynome/alpine-drone-ci
    commands:
      - npm run postpublish
      - cat ./.tags
      - exit 1

  npm_publish:
    when:
      event: tag
    image: plugins/npm
    username: shynome
    email: shynome@gmail.com
    secrets: [ npm_token ]
    
  dokcer_publish:
    when:
      event: tag
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: shynome/alpine-drone-ci
  
  dev_docker_publish:
    when:
      branch: dev
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    dockerfile: dev.Dockerfile
    repo: shynome/alpine-drone-ci
    tags: [ dev ]
