
pipeline:

  npm_publish:
    when:
      event: tag
    image: plugins/npm
    username: shynome
    email: shynome@gmail.com
    secrets: [ NPM_TOKEN ]
    
  dokcer_publish:
    when:
      event: tag
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: shynome/alpine-drone-ci
    auto_tag: true
  
  dev_docker_publish:
    when:
      branch: dev
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: shynome/alpine-drone-ci
    tags: [ dev ]


